#!/bin/bash -e

cd "$(dirname $0)"

if [ "$2" == "" ]; then
    echo "Usage: $0 <vm> <launchpad-id>"
    exit 1
fi

./aoi-ssh $1 sudo rm /root/.ssh/authorized_keys
./aoi-ssh $1 sudo -H ssh-import-id $2

