#!/bin/bash -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$*" != "" ]; then
    SYNC="$@"
else
    SYNC="trusty xenial bionic"
fi

$SCRIPT_DIR/aoi-fetch-releases $SYNC
$SCRIPT_DIR/aoi-verify-and-link $SYNC
