#!/bin/bash -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$2" == "" ]; then
    echo "Usage: $0 <vm> <launchpad-id>"
    exit 1
fi

$SCRIPT_DIR/aoi-ssh $1 sudo rm /root/.ssh/authorized_keys
$SCRIPT_DIR/aoi-ssh $1 sudo -H ssh-import-id $2
