#!/bin/bash -e

if [ "$1" == "" ]; then
    echo "Must supply a VM name."
    exit 1
fi

NAME=$1
IMAGES_DIR="$(aoi config get images_dir $HOME/.cloud-images)"

IMAGE=$IMAGES_DIR/$NAME.img
CDROM=$IMAGES_DIR/${NAME}-config.iso

# We use || true here because it might not be running.
virsh destroy $NAME || true

# Bug: for some reason, --remove-all-storage does not seem to work
# in all cases.
virsh undefine $NAME  # --remove-all-storage

# ... so we'll remove them by hand.
rm -f $IMAGE

# The CD-ROM might not exist if this was just a test host.
rm -f $CDROM || true
