#!/bin/bash -e

HOSTNAME=$1

if [ "$HOSTNAME" == "" ]; then
    echo "Must supply a hostname."
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ip -4 neigh show dev virbr0 | grep $($SCRIPT_DIR/aoi-get-mac $HOSTNAME) | awk '{ print $1 }'
