#!/bin/bash -e

HOSTNAME=$1

if [ "$HOSTNAME" == "" ]; then
    echo "Must supply a hostname first."
    exit 1
fi

IP=$(./aoi-get-ip-via-arp $HOSTNAME)

if [ "$IP" == "" ]; then
    echo "IP address could not be found for host: $HOSTNAME"
    exit 1
fi

shift

./aoi-untrusted-ssh ubuntu@"$IP" "$@"
