#!/bin/bash -e

if [ "$1" == "" ]; then
    echo "Must supply releases to fetch. Example:"
    echo "    $0 trusty xenial"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
while [ "$1" != "" ]; do
    echo "Fetching $1..."
    $SCRIPT_DIR/aoi-fetch-latest-image $1
    shift
done
