#!/bin/bash -e

if [ $(id -u) -eq 0 ]; then
    echo "Please run this script as a normal user."
    echo "You will be prompted by 'sudo' if necessary."
    exit 1
fi

sudo apt-get update
sudo apt-get install -yu \
    libvirt-bin qemu-kvm virtinst uuid apparmor-profiles apparmor-utils
sudo usermod -a -G libvirtd,kvm $USER
sudo aa-complain /usr/lib/libvirt/virt-aa-helper

cd "$(dirname $0)"

if ! id | awk '{ print $3 }' | grep '(libvirtd)' | grep -q '(kvm)'; then
    echo ""
    echo "Your user was just added to the 'libvirtd' and 'kvm' groups, but"
    echo "membership was not yet taken effect."
    echo "You need to log out, log back in, and then re-run:"
    echo ""
    echo "    $(pwd)/$(basename $0)"
    echo ""
    exit 1
fi

./aoi-configure-networks
./aoi-sync
