#!/bin/bash -e

if [ $(id -u) -eq 0 ]; then
    echo "Please run this script as a normal user."
    echo "You will be prompted by 'sudo' if necessary."
    exit 1
fi

sudo apt-get update
sudo apt-get install -yu \
    libvirt-bin qemu-kvm virtinst uuid apparmor-profiles apparmor-utils \
    genisoimage
sudo usermod -a -G libvirtd,kvm $USER
sudo aa-complain /usr/lib/libvirt/virt-aa-helper

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! id | awk '{ print $3 }' | grep '(libvirtd)' | grep -q '(kvm)'; then
    echo ""
    echo "Your user was just added to the 'libvirtd' and 'kvm' groups, but"
    echo "membership was not yet taken effect."
    echo "You need to log out, log back in, and then re-run:"
    echo ""
    echo "    $(pwd)/$(basename $0)"
    echo ""
    exit 1
fi

$SCRIPT_DIR/aoi-configure-networks
$SCRIPT_DIR/aoi-sync
$SCRIPT_DIR/aoi-generate-ssh-keys
