#!/bin/bash -e

cd "$(dirname $0)"
IMAGES_DIR="$(aoi config get images_dir $HOME/.cloud-images)"

function error {
    echo "$@"
    exit 1
}


if [ "$1" == "" ]; then
    echo "Must supply a VM name to create."
    exit 1
else
    NAME=$1
fi

HOSTNAME=$NAME
INSTANCE=$NAME

TARGET_IMAGE=$HOSTNAME.img

virsh pool-define-as \
    --name cloud-images --type dir --target $IMAGES_DIR 2> /dev/null \
    || echo "Image pool already exists: $IMAGES_DIR"

pushd $IMAGES_DIR > /dev/null 2>&1
for image in ${HOSTNAME}-{1,2,3,4,5,6,7,8,9}.img; do
    qemu-img create -f qcow2 $image 3G
    qemu-img info $image
    IMAGE_ARGS="$IMAGE_ARGS --disk=$IMAGES_DIR/$image,bus=scsi"
done
popd > /dev/null 2>&1

virt-install \
    --name $HOSTNAME \
    --virt-type kvm --hvm --noautoconsole \
    --boot network,hd \
    --import \
    $IMAGE_ARGS \
    --memory 1024 \
    --network network=testnet,mac=$(./aoi-get-mac testnet-$HOSTNAME) \
    --network network=testnet,mac=$(./aoi-get-mac testnet-2-$HOSTNAME)

virsh destroy $HOSTNAME

echo "Test host created: $HOSTNAME"
