#!/bin/bash -e

if [ "$1" == "" ]; then
    echo "Must supply releases to fetch. Example:"
    echo "    $0 trusty xenial"
    exit 1
fi

cd "$(dirname $0)"
while [ "$1" != "" ]; do
    echo "Fetching $1..."
    ./aoi-fetch-latest-image $1
    shift
done
