#!/bin/bash -e

sudo service libvirt-bin stop
PIDS=$(cat /var/run/libvirt/network/*.pid)
for pid in $PIDS; do
    sudo kill $PID
done
sudo rm /var/lib/libvirt/dnsmasq/*.status
sudo service libvirt-bin start

