#!/bin/bash -xe

if [ "$1" == "" ]; then
    echo "Must supply a VM name."
    exit 1
fi

NAME=$1
IMAGES=/var/lib/libvirt/images

IMAGE=$IMAGES/$NAME.img
CDROM=$IMAGES/${NAME}-config.iso

sudo virsh destroy $NAME --graceful

# Bug: for some reason, --remove-all-storage does not seem to work
# in all cases.
sudo virsh undefine $NAME  # --remove-all-storage

# ... so we'll remove them by hand.
sudo rm -f $IMAGE $CDROM

