#!/usr/bin/env python3

from binascii import hexlify
from hashlib import sha256
from sys import argv, exit

if len(argv) <= 1:
    exit(1)
mac = b'525400' + hexlify(sha256(argv[1].encode('utf-8')).digest())[:6]
mac = mac.decode('utf-8')
print(':'.join(mac[i:i+2] for i in range(0, len(mac), 2)))

