#!/usr/bin/env python3

from lxml import etree
import sys

def main():
    if len(sys.argv) >= 2:
        filename = sys.argv[1]
    else:
        sys.stderr.write("Must supply a filename.\n")
        sys.exit(1)
    if len(sys.argv) >= 3:
        domain = sys.argv[2]
    else:
        domain = None
    parser = etree.XMLParser(remove_blank_text=True)
    doc = etree.parse(filename, parser).getroot()
    evaluator = etree.XPathEvaluator(doc)
    xdomains = evaluator('/network/domain')
    for element in xdomains:
        element.getparent().remove(element)
    if domain is not None:
        # No domain defined, so let's create one.
        xnetwork = evaluator('/network')[0]
        xnetwork.append(etree.XML("<domain name='%s'/>" % (domain)))
    sys.stdout.write(etree.tostring(doc, pretty_print=True).decode('utf-8'))
    sys.stdout.write('\n')

if __name__ == '__main__':
    main()
